### ISSUE TITLE
Mark latest version on CurseForge as 1.12.1

### ISSUE THREAD

**Issue by xbony2** [Towdium/JustEnoughCharacters#12]
Thank you ^_^

**Comment by Towdium** [comment]
Thanks for notifying me! I'll do it now.

**Comment by xbony2** [comment]
Looks good 👍 thanks

**Comment by Towdium** [comment]
By the way, are you a foreigner? El... I mean not Chinese. 

There is currently an issue that sound of "铝" or "吕" is marked as "lu" in this mod, while the actual sound should be "lv" or, more accurately, "lǚ". 

I think it's better to clearify this since it should be clear to Chinease users while could be misleading to foreigners.

**Comment by xbony2** [comment]
Err yes, I am an American spy :P I don't know enough about Chinese to make any sort of comment about its transliteration.
